### ISSUE TITLE
TypeError: TwitchRequest is not a constructor

### ISSUE THREAD

**Issue by JDittmerCOM** [destial/twitchrequest#1]
Hi, I've followed the documentation as far as possible, but I keep getting the same error.
Maybe you can help me further. 

```
const twitchClient = new TwitchRequest(TwitchClientOptions);
                     ^

TypeError: TwitchRequest is not a constructor
    at Object.<anonymous> (/root/twitchStreamBot/index.js:27:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

My code snippet. 
```javascript
const { TwitchRequest } = require("twitchrequest");
const TwitchClientOptions = {
    channels: [],
    client_id: "xxxxxxxxxxxxxxxxxxxx",
    client_secret: "xxxxxxxxxxxxxxxxxxxx",
    interval: 3
};
const twitchClient = new TwitchRequest(TwitchClientOptions);
```

**Comment by destial** [comment]
Hi there Justin!

Sorry for the misunderstanding, the documentation is outdated and I have
now updated it to show the correct usage.
Here is the correct usage:

const { Client } = require("twitchrequest");
const TwitchClientOptions = {
    channels: [],
    client_id: "xxxxxxxxxxxxxxxxxxxx",
    client_secret: "xxxxxxxxxxxxxxxxxxxx",
    interval: 3
};
const twitchClient = new Client(TwitchClientOptions);

**Comment by destial** [comment]
Hi there Justin!

Sorry for the misunderstanding, the documentation is outdated and I have
now updated it to show the correct usage.
Here is the correct usage:
```
const { Client } = require("twitchrequest");
const TwitchClientOptions = {
    channels: [],
    client_id: "xxxxxxxxxxxxxxxxxxxx",
    client_secret: "xxxxxxxxxxxxxxxxxxxx",
    interval: 3
};
const twitchClient = new Client(TwitchClientOptions);
```

**Comment by JDittmerCOM** [comment]
Thanks, that's how it works.

But I still have one short question. The **const { Client } = ...** is then more or less generally blocked, right?
Or could I use **const Client = ....** for something else then too?

**Comment by destial** [comment]
const { Client } = ... takes the Client class only from the library, if you want to get all the classes, you can do
```
const TwitchRequest = require('twitchrequest')
const TwitchClientOptions = {
...
}
const client = new TwitchRequest.Client(TwitchClientOptions);
```
That way, you have access to TwitchRequest.StreamData and etc.

**Comment by JDittmerCOM** [comment]
All right, thank you.
